#-------------------------------------------------------------------------------
# Copyright (C) 2017 Resin.io, UNI Passau, FBK.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Resin.io, UNI Passau, FBK - initial API and implementation
#-------------------------------------------------------------------------------
version: '2'

services:

#  agile-dbus:
#    container_name: agile-dbus
#    image: agileiot/agile-dbus-$AGILE_ARCH:v0.1.4
#    # build: apps/agile-dbus
#    restart: always
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#
#  agile-devicemanager:
#    command: [ "bash", "/usr/src/app/scripts/start.sh", "DeviceManager" ]
#    container_name: agile-devicemanager
#    image: agileiot/agile-core-$AGILE_ARCH:v0.2.17
#    # build: apps/agile-core
#    depends_on:
#      - agile-dbus
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#      - $DATA/core/plugins:/usr/src/app/plugins
#    environment:
#      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
#    restart: always
#    privileged: true
#
#  agile-protocolmanager:
#    command: [ "bash", "/usr/src/app/scripts/start.sh", "ProtocolManager" ]
#    container_name: agile-protocolmanager
#    image: agileiot/agile-core-$AGILE_ARCH:v0.2.17
#    # build: apps/agile-core
#    depends_on:
#      - agile-dbus
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#      - $DATA/core/plugins:/usr/src/app/plugins
#    environment:
#      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
#    restart: always
#    privileged: true
#
#  agile-devicefactory:
#    command: [ "bash", "/usr/src/app/scripts/start.sh", "DeviceFactory" ]
#    container_name: agile-devicefactory
#    image: agileiot/agile-core-$AGILE_ARCH:v0.2.17
#    # build: apps/agile-core
#    depends_on:
#      - agile-dbus
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#      - $DATA/core/plugins:/usr/src/app/plugins
#    environment:
#      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
#    restart: always
#    privileged: true
#
#  agile-core:
#    command: [ "bash", "/usr/src/app/scripts/start.sh", "http" ]
#    container_name: agile-core
#    # build: apps/agile-core
#    image: agileiot/agile-core-$AGILE_ARCH:v0.2.17
#    depends_on:
#      - agile-dbus
#      - agile-devicemanager
#      - agile-devicefactory
#      - agile-protocolmanager
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#    environment:
#      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
#    ports:
#      - 8080:8080/tcp
#    restart: always
#    privileged: true
#
#  agile-ui:
#    container_name: agile-ui
#    image: agileiot/agile-ui-$AGILE_ARCH:v2.5.1
#    # build: apps/agile-ui
#    restart: always
#    depends_on:
#      - agile-core
#    ports:
#      - 2000:1337/tcp
#
#  agile-osjs:
#    container_name: agile-osjs
#    image: agileiot/agile-osjs-$AGILE_ARCH:v0.4.0
#    # build: apps/agile-osjs
#    depends_on:
#      - agile-core
#    environment:
#      - AGILE_HOST=$AGILE_HOST
#    ports:
#      - 8000:8000/tcp
#    restart: always
#    volumes:
#      - /etc/hostname:/etc/hostname

  agile-wordpress:
    build:
      context: ./apps/wordpress
      dockerfile: php7.0/apache/Dockerfile
    container_name: agile-wordpress
    restart: always
    ports:
      - 80:80/tcp
    depends_on:
      - sql-db
    volumes:
      - $DATA/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: sql-db:3306
      WORDPRESS_DB_PASSWORD: root

  sql-db:
    #In a rpi use this one
    #image: hypriot/rpi-mysql
    #For intel use this one
    image: mysql:5.5
    container_name: sql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306/tcp

  agile-security:
    container_name: agile-security
    image: agileiot/agile-security-$AGILE_ARCH:mongodb
    #build: apps/agile-security
    hostname: agile-security
    volumes:
      - $DATA/security/idm/conf:/root/idm.conf
      - $DATA/security/idm/db:/root/idm.db
      - /etc/hostname:/etc/hostname
    environment:
      - DOCKER_CONF=/root/idm.conf
      - AGILE_HOST=$AGILE_HOST
    ports:
      - 3000:3000/tcp
      - 1444:1444/tcp
      - 1443:1443/tcp
    restart: always

  wso2is:
    image: isim/wso2is
    container_name: wso2is
    restart: always
    ports:
      - 9444:9443/tcp

  wso2is-db:
    #In a rpi use this one
    #image: hypriot/rpi-mysql
    #For intel use this one
    image: mysql:5.5
    container_name: sql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306/tcp

############## MONGODB ###############
  ##INTEL
  mongo:
    image: mongo:3.2.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: agile
      MONGO_INITDB_ROOT_PASSWORD: secret
    expose:
      - 27017:27017/tcp
    restart: always
    volumes:
      - $DATA/mongo/db/:/data/db
    command: mongod --auth

  ##ARM
#  mongo:
#    build: https://github.com/Agile-IoT/rpi-mongodb.git
#    expose:
#      - 27017:27017/tcp
#    restart: always
#    volumes:
#      - $DATA/mongo/db/:/data/db